inherit_from: .rubocop_todo.yml

# Regexp#match? has only been available since Ruby v2.4
Performance/RegexpMatch:
  Enabled: false

# Even the reference in the documentation suggests that you should prefer
# `alias_method` vs `alias`, so I don't understand why that isn't the default.
Style/Alias:
  EnforcedStyle: prefer_alias_method

# Enumerable#each_with_object only available since Ruby v1.9
Style/EachWithObject:
  Enabled: false

# Kernel#format has only supported named references since Ruby v1.9
Style/FormatStringToken:
  EnforcedStyle: unannotated

# ruby19 style has only been supported since Ruby v1.9
Style/HashSyntax:
  EnforcedStyle: hash_rockets

# I'm not keen on this cop, because it's easy to miss the conditional
# I think the results are particularly unhelpful when Metrics/LineLength is big
Style/IfUnlessModifier:
  Enabled: false
